EXPERIMENT:
  NAME: ""
  TAG: "cam,res110,res32"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CAM"
  TEACHER: "resnet110"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
CAM:
  LOSS:
    FEAT_WEIGHT: 1.0
    