EXPERIMENT:
  NAME: ""
  TAG: "cam,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CAM"
  TEACHER: "ResNet101"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
#   BATCH_SIZE: 128
#   EPOCHS: 200
#   LR: 0.1
#   LR_DECAY_STAGES: [60, 120, 160]
#   LR_DECAY_RATE: 0.2
#   WEIGHT_DECAY: 0.0005
#   MOMENTUM: 0.9
#   TYPE: "SGD"
