EXPERIMENT:
  NAME: ""
  TAG: "cam,shuv1,res20"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CAM"
  TEACHER: "ShuffleV1"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
CAM:
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 1.0