EXPERIMENT:
  NAME: ""
  TAG: "cam,res34,res18"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 16
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "CAM"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 512
  GRAD_ACC: 1
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [15, 30, 45]
  LR_DECAY_RATE: 0.2
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
CAM:
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 2.0
