EXPERIMENT:
  NAME: ""
  TAG: "dkd_cam,res56,res20"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "DKD_CAM"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 2.0
  CE_WEIGHT: 2.0
CAM:
  LOSS:
    FEAT_WEIGHT: 0.001