EXPERIMENT:
  NAME: ""
  TAG: "cam,res34,shuv1"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "CAM"
  TEACHER: "ResNet34"
  STUDENT: "ShuffleV1"
SOLVER:
  BATCH_SIZE: 1
  GRAD_ACC: 
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
DKD:
  CE_WEIGHT: 1.0
  BETA: 2.0
  T: 1.0
  WARMUP: 1
